swagger: '2.0'
info:
  description: >
    Management equipments API - MicroService.
  version: 1.0.0
  title: InventarioAPI
  contact:
    email: adriely.nara@gmail.com
host: localhost:8090
basePath: /
tags:
  - name: equipment
    description: Definition of equipment
schemes:
  - http
  - https
paths:
  /equipments:
    get:
      tags:
        - equipment
      summary: List equipments
      description: List equipments
      operationId: listEquipments
      produces:
        - application/json
        - text/csv
      responses:
        '200':
          description: successfully performed.
          headers:
            X-Total-Elements:
              type: integer
              description: Total equipment available.
            X-Total-Pages:
              type: integer
              description: Total equipment pages available.
            Link:
              type: string
              description: Links to navegation.
          schema:
            type: array
            items:
              $ref: '#/definitions/EquipmentFinal'
    post:
      tags:
        - equipment
      summary: Add um equipment
      description: ''
      operationId: createEquipment
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: register equipment
          required: true
          schema:
            $ref: '#/definitions/Equipment'
      responses:
        '200':
          description: successfully performed.
          headers:
            Location:
              type: string
              description: link to new equipment
          schema:
            $ref: '#/definitions/Equipment'
        '400':
          description: Invalid Input
        '409':
          description: inconsistent model
          schema:
            $ref: '#/definitions/Equipment'
  '/equipments/{codeEquipment}':
    get:
      tags:
        - equipment
      summary: recover equipment
      description: ''
      operationId: getEquipment
      produces:
        - application/json
      parameters:
        - name: codeEquipment
          in: path
          description: Equipment code
          required: true
          type: integer
      responses:
        '200':
          description: successfully performed.
          schema:
            $ref: '#/definitions/EquipmentFinal'
        '404':
          description: Equipment not found 
    delete:
      tags: 
        - equipment
      summary: Remove equipment
      description: ''
      operationId: removeEquipment
      parameters: 
        - name: codeEquipment
          in: path
          description: Equipment code
          required: true
          type: integer
      responses:
        '200':
          description: successfully performed.
        '404':
          description: Equipment not found
definitions:
  Equipment:
    type: object
    properties:
      codeEquipment:
        description: "Identification equipment code"
        type: integer
        format: "int64"
      modelEquipment:
        type: string
      valEquipment:
        type: "number"
      dtEquipment:
        type: string
        format: date
      typeEquipment:
        type: integer
        format: "int64"
      imageEquipment:
       description: "base64 format image"
       type: string
  EquipmentFinal:
    type: object
    properties:
      codeEquipment:
        description: "Identification equipment code"
        type: integer
        format: "int64"
      modelEquipment:
        type: string
      valEquipment:
        type: "number"
      valEquipmentWithPercent:
        type: "number"
      dtEquipment:
        type: string
        format: date
      typeEquipment:
        type: integer
        format: "int64"
      imageEquipment:
       description: "base64 format image"
       type: string
              