swagger: '2.0'
info:
  description: >
    Management equipments API - MicroService.
  version: 1.0.0
  title: InventarioAPI
  contact:
    email: adriely.nara@gmail.com
host: localhost:8090
basePath: /
tags:
  - name: equipment
    description: Definition of equipment
schemes:
  - http
  - https
paths:
  /equipments:
    get:
      tags:
        - equipment
      summary: List equipments
      description: List equipments
      operationId: listEquipments
      produces:
        - application/json
        - text/csv
      responses:
        '200':
          description: Operacao realizada com sucesso
          headers:
            X-Total-Elements:
              type: integer
              description: Total de equipments disponiveis para navegacao.
            X-Total-Pages:
              type: integer
              description: Total de paginas disponiveis par navegacao.
            Link:
              type: string
              description: Links para navegacao entre paginas.
          schema:
            type: array
            items:
              $ref: '#/definitions/EquipmentFinal'
    post:
      tags:
        - equipment
      summary: Adiciona um equipment
      description: ''
      operationId: createEquipment
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: equipment a ser armazenado
          required: true
          schema:
            $ref: '#/definitions/Equipment'
      responses:
        '200':
          description: Operacao realizada com sucesso
          headers:
            Location:
              type: string
              description: link para um novo equipment
          schema:
            $ref: '#/definitions/Equipment'
        '400':
          description: Entrada invalida
        '409':
          description: Modelo de Consistencia
          schema:
            $ref: '#/definitions/Equipment'
  '/equipments/{idEquipment}':
    get:
      tags:
        - equipment
      summary: Recupera um equipment
      description: ''
      operationId: getEquipment
      produces:
        - application/json
      parameters:
        - name: idEquipment
          in: path
          description: ID do Equipment
          required: true
          type: integer
      responses:
        '200':
          description: Operacao realizada com sucesso
          schema:
            $ref: '#/definitions/EquipmentFinal'
        '404':
          description: Equipment nao encontrado
    put:
      tags: 
        - equipment
      summary: Atualiza um equipment
      description: ''
      operationId: updateEquipment
      produces: 
        - application/json
      consumes: 
        - application/json
      parameters: 
        - name: idEquipment
          in: path
          description: ID do Equipment
          required: true
          type: string
        - in: body
          name: body
          description: Equipment a ser atualizado
          required: true
          schema:
            $ref: '#/definitions/Equipment'
      responses:
        '200':
          description: Operacao realizada com sucesso
          headers:
            Location:
              type: string
              description: link para um novo Equipment
          schema:
            $ref: '#/definitions/Equipment'
        '400':
          description: Entrada invalida
          schema:
            $ref: '#/definitions/Equipment'
        '409':
          description: Conflito
          schema:
            $ref: '#/definitions/Equipment'  
    delete:
      tags: 
        - equipment
      summary: Remove um Equipment
      description: ''
      operationId: removerEquipment
      parameters: 
        - name: idEquipment
          in: path
          description: ID do Equipment
          required: true
          type: integer
      responses:
        '200':
          description: Operacao realizada com sucesso
        '404':
          description: Equipment nao encontrado
definitions:
  Equipment:
    type: object
    properties:
      codeEquipment:
        description: "Identificador do equipment"
        type: integer
        format: "int64"
      modelEquipment:
        type: string
      valEquipment:
        type: integer
      dtEquipment:
        type: string
        format: date
      typeEquipment:
        type: integer
        format: "int64"
      imageEquipment:
       description: "Recebe imagem em formato de String base64"
       type: string
  EquipmentFinal:
    type: object
    properties:
      codeEquipment:
        description: "Identificador do equipment"
        type: integer
        format: "int64"
      modelEquipment:
        type: string
      valEquipment:
        type: integer
      valEquipmentWithPercent:
        type: integer
      dtEquipment:
        type: string
        format: date
      typeEquipment:
        type: integer
        format: "int64"
      imageEquipment:
       description: "Recebe imagem em formato de String base64"
       type: string
              